### PR TITLE
Setting up some tests

### PR DESCRIPTION
**Pull request by tek08**
* **Please check if the PR fulfills these requirements**
- [ ] Does the code follow [Google's Style Guides](https://google.github.io/styleguide/) for the chosen language(s)?
- [ ] Has the code been formatted with Prettier using the default settings for the chosen language(s)?
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Introduces tests for phonescrubber

* **What is the current behavior?** (You can also link to an open issue here)
there are no tests

* **What is the new behavior (if this is a feature change)?**
now there are tests, especially when you run `python -m pytest`

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
need to run `pipenv sync --dev`

* **Other information**:

### CODE REVIEW

**Comment by tek08** [comment]
#2

**Comment by iandees** [comment]
I'm also going to sneak #3 in here as well, since you're adding tests to run in CI 😄.

**Review by iandees — APPROVED** [review]
Thanks for adding these!

**Comment by tek08** [comment]
download

**Pull request merged**
